name: Delete Failed Workflow Runs

on:
  workflow_dispatch:  # Manuelle Ausführung erlaubt

jobs:
  delete_failed_runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        run: |
          # Install GitHub CLI using official package
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: |
          # Authenticate GitHub CLI with the GitHub token
          echo "${{ secrets.TOKEN }}" | gh auth login --with-token

      - name: List all workflow runs and delete failed ones
        run: |
          # Get the list of all workflow runs in the repository
          runs=$(gh api repos/${{ github.repository }}/actions/runs -q '.workflow_runs[] | select(.status=="failure") | .id')

          # Loop through the failed runs and delete them
          if [ -z "$runs" ]; then
            echo "No failed runs found."
          else
            for run_id in $runs; do
              echo "Deleting failed workflow run with ID: $run_id"
              gh api repos/${{ github.repository }}/actions/runs/$run_id/attempts --method DELETE
            done
          fi
